version: '3.8'
services:
  ambev.developerevaluation.webapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=DeveloperEvaluationDb;User Id=postgres;Password=docker;
    ports:
      - "5000:8080"
      - "5001:8081"
    networks:
      - shared-net

networks:
  shared-net:
    external: true
